Be a little bit less verbose in bootstrap-haskell

diff --git a/bootstrap-haskell b/bootstrap-haskell
--- a/bootstrap-haskell
+++ b/bootstrap-haskell
@@ -12,8 +12,7 @@ die() {
 
 edo()
 {
-    (>&2 printf "\\033[0;35m%s\\033[0m\\n" "$*")
-    "$@" || exit 2
+    "$@" || die "\"$*\" failed!"
 }
 
 echo
@@ -48,7 +47,7 @@ if command -V "ghcup" >/dev/null 2>&1 ; then
 		edo ghcup upgrade
 	fi
 else
-	edo curl https://raw.githubusercontent.com/haskell/ghcup/master/ghcup > "${GHCUP_INSTALL_BASE_PREFIX}"/.ghcup/bin/ghcup
+	edo curl --silent https://raw.githubusercontent.com/haskell/ghcup/master/ghcup > "${GHCUP_INSTALL_BASE_PREFIX}"/.ghcup/bin/ghcup
 	edo chmod +x "${GHCUP_INSTALL_BASE_PREFIX}"/.ghcup/bin/ghcup
 
 	cat <<-EOF > "${GHCUP_INSTALL_BASE_PREFIX}"/.ghcup/env || die "Failed to create env file"
